// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTuberGame.API.Data;

#nullable disable

namespace YouTuberGame.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260210121500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("YouTuberGame.Shared.Models.Character", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BaseDesign")
                        .HasColumnType("int");

                    b.Property<int>("BaseEditing")
                        .HasColumnType("int");

                    b.Property<int>("BaseFilming")
                        .HasColumnType("int");

                    b.Property<int>("BasePlanning")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PassiveSkillDesc")
                        .HasColumnType("longtext");

                    b.Property<float>("PassiveSkillValue")
                        .HasColumnType("float");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Specialty")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = "char_001",
                            BaseDesign = 10,
                            BaseEditing = 10,
                            BaseFilming = 30,
                            BasePlanning = 10,
                            CharacterName = "김촬영",
                            PassiveSkillValue = 0f,
                            Rarity = 0,
                            Specialty = 0
                        },
                        new
                        {
                            CharacterId = "char_002",
                            BaseDesign = 10,
                            BaseEditing = 30,
                            BaseFilming = 10,
                            BasePlanning = 10,
                            CharacterName = "박편집",
                            PassiveSkillValue = 0f,
                            Rarity = 0,
                            Specialty = 1
                        },
                        new
                        {
                            CharacterId = "char_003",
                            BaseDesign = 10,
                            BaseEditing = 10,
                            BaseFilming = 10,
                            BasePlanning = 30,
                            CharacterName = "이기획",
                            PassiveSkillValue = 0f,
                            Rarity = 0,
                            Specialty = 2
                        },
                        new
                        {
                            CharacterId = "char_004",
                            BaseDesign = 30,
                            BaseEditing = 10,
                            BaseFilming = 10,
                            BasePlanning = 10,
                            CharacterName = "최디자인",
                            PassiveSkillValue = 0f,
                            Rarity = 0,
                            Specialty = 3
                        },
                        new
                        {
                            CharacterId = "char_005",
                            BaseDesign = 15,
                            BaseEditing = 15,
                            BaseFilming = 15,
                            BasePlanning = 40,
                            CharacterName = "강PD",
                            PassiveSkillValue = 0f,
                            Rarity = 1,
                            Specialty = 2
                        },
                        new
                        {
                            CharacterId = "char_006",
                            BaseDesign = 20,
                            BaseEditing = 30,
                            BaseFilming = 50,
                            BasePlanning = 20,
                            CharacterName = "정프로",
                            PassiveSkillDesc = "촬영 품질 +10%",
                            PassiveSkillValue = 0.1f,
                            Rarity = 2,
                            Specialty = 0
                        },
                        new
                        {
                            CharacterId = "char_007",
                            BaseDesign = 40,
                            BaseEditing = 40,
                            BaseFilming = 40,
                            BasePlanning = 60,
                            CharacterName = "천재 크리에이터",
                            PassiveSkillDesc = "전체 스탯 +15%",
                            PassiveSkillValue = 0.15f,
                            Rarity = 3,
                            Specialty = 2
                        });
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.PlayerCharacter", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Breakthrough")
                        .HasColumnType("int");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("InstanceId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.PlayerData", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ChannelPower")
                        .HasColumnType("bigint");

                    b.Property<int>("ExpChips")
                        .HasColumnType("int");

                    b.Property<int>("GachaTickets")
                        .HasColumnType("int");

                    b.Property<int>("Gems")
                        .HasColumnType("int");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<int>("StudioLevel")
                        .HasColumnType("int");

                    b.Property<long>("Subscribers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.PlayerCharacter", b =>
                {
                    b.HasOne("YouTuberGame.Shared.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YouTuberGame.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.PlayerData", b =>
                {
                    b.HasOne("YouTuberGame.Shared.Models.User", "User")
                        .WithOne("PlayerData")
                        .HasForeignKey("YouTuberGame.Shared.Models.PlayerData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YouTuberGame.Shared.Models.User", b =>
                {
                    b.Navigation("PlayerData");
                });
#pragma warning restore 612, 618
        }
    }
}
